apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ctfd-2022-chall-uccdi-hpa
  labels:
    ctfd.chall.pod: ctfd-2022-uccdi-pod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ctfd-2022-chall-uccdi-deployment
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 10
status:
  observedGeneration: 1
  currentReplicas: 1
  desiredReplicas: 1
  currentMetrics:
  - type: Resource
    resource:
      name: cpu
      current:
        averageUtilization: 0
        averageValue: 0
