apiVersion: v1
kind: Service
metadata:
  name: ctfd-2022-chall-uccdi-service
  namespace: challs
  labels:
    ctfd.chall.service: ctfd-2022-chall-uccdi-service
spec:
  selector:
    ctfd.chall.pod: ctfd-2022-uccdi-pod
  type: ClusterIP
  ports:
  - name: 'http'
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ctfd-2022-chall-uccdi
  namespace: challs
spec:
  type: ExternalName
  externalName: ctfd-2022-chall-uccdi-deployment.default.svc.cluster.local
