apiVersion: v1
kind: Namespace
metadata:
  name: site
---
apiVersion: v1
kind: Namespace
metadata:
  name: ctfd
---
apiVersion: v1
kind: Namespace
metadata:
  name: database
---
apiVersion: v1
kind: Namespace
metadata:
  name: redis
---
apiVersion: v1
kind: Namespace
metadata:
  name: challs
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
