apiVersion: v1
kind: Namespace
metadata:
  name: site
  labels:
    name: site
---
apiVersion: v1
kind: Namespace
metadata:
  name: ctfd
  labels:
    name: ctfd
---
apiVersion: v1
kind: Namespace
metadata:
  name: database
  labels:
    name: database
---
apiVersion: v1
kind: Namespace
metadata:
  name: redis
  labels:
    name: redis
---
apiVersion: v1
kind: Namespace
metadata:
  name: challs
  labels:
    name: challs
