apiVersion: v1
kind: Service
metadata:
  name: ctfd-2022-service
  namespace: ctfd
spec:
  type: ClusterIP
  ports:
  - name: 'http'
    port: 8000
    targetPort: 8000
  selector:
    ctfd.2022.pod: ctfd-2022-pod
---
apiVersion: v1
kind: Service
metadata:
  name: ctfd-2022
  namespace: ctfd
spec:
  type: ExternalName
  externalName: ctfd-2022-deployment.default.svc.cluster.local
