apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctfd-nginx-deployment
  namespace: website
  labels:
    ctfd.nginx.service: ctfd-nginx-service
spec:
  replicas: 1
  selector:
    matchLabels:
      ctfd.nginx.service: ctfd-nginx-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        ctfd.nginx.service: ctfd-nginx-service
    spec:
      containers:
      - image: doombringerazurai/ctfd-nginx:1.0
        name: ctfd-nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "30m"
          limits:
            cpu: "100m"
      restartPolicy: Always
      tolerations:
        - key: "type"
          operator: "Equal"
          value: "challs"
          effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: ctfd-nginx-service
  namespace: website
  labels:
    ctfd.nginx.service: ctfd-nginx-service
spec:
  selector:
    ctfd.nginx.service: ctfd-nginx-service
  type: LoadBalancer
  ports:
  - name: 'http'
    port: 80
    targetPort: 80
    nodePort: 30000
  - name: 'ctfd-2021'
    port: 3000
    targetPort: 3000
    nodePort: 31001
  - name: 'ctfd-2022'
    port: 3001
    targetPort: 3001
    nodePort: 31002
status:
  loadBalancer: {}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ctfd-nginx-hpa
  namespace: website
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ctfd-nginx-deployment
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
#  - type: Resource
#    resource:
#      name: memory
#      target:
#        type: Utilization
#        averageUtilization: 50
  behavior:
    scaleDown:
      policies:
      - type: Pods
        value: 3
        periodSeconds: 60
      - type: Percent
        value: 10
        periodSeconds: 60
      stabilizationWindowSeconds: 300
status:
  observedGeneration: 1
  currentReplicas: 1
  desiredReplicas: 1
  currentMetrics:
  - type: Resource
    resource:
      name: cpu
      current:
        averageUtilization: 0
        averageValue: 0
