apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctfd-2021-deployment
  namespace: ctfd
spec:
  replicas: 1
  selector:
    matchLabels:
      ctfd.2021.pod: ctfd-2021-pod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        ctfd.2021.pod: ctfd-2021-pod
    spec:
      containers:
      - image: doombringerazurai/ctfd:1.0
        name: ctfd-2021
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: ctfd-env-configmap
        env:
        - name: DB_SERVER
          value: 'ctfd-db-2021-service.database.svc.cluster.local'
        volumeMounts:
        - name: ctfd-2021-log-pvc
          mountPath: '/var/log/CTFd'
        - name: ctfd-2021-uploads-pvc
          mountPath: '/var/uploads'
        - name: ctfd-db-2021-secret
          mountPath: '/etc/ctfd-db'
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 60
            #initContainers:
        #      - name: wait-redis
        #        image: busybox:1.28
        #        command: ['sh', '-c', 'until nslookup ctfd-redis-master.redis.svc.cluster.local; do echo waiting for db; sleep 2; done']
        #      - name: wait-database
        #        image: busybox:1.28
        #        command: ['sh', '-c', 'until nslookup ctfd-db-2021-service.database.svc.cluster.local; do echo waiting for db; sleep 2; done']
      restartPolicy: Always
      tolerations:
        - key: 'type'
          operator: 'Equal'
          value: 'site'
          effect: 'NoSchedule'
      volumes:
      - name: ctfd-2021-log-pvc
        persistentVolumeClaim:
          claimName: ctfd-2021-log-pvc
      - name: ctfd-2021-uploads-pvc
        persistentVolumeClaim:
          claimName: ctfd-2021-uploads-pvc
      - name: ctfd-db-2021-secret
        secret:
          secretName: ctfd-db-2021
