apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ctfd-2021-log-pvc
  namespace: ctfd
spec:
  storageClassName: nfs
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 400Mi
  selector:
    matchLabels:
      name: ctfd-2021-log-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ctfd-2021-uploads-pvc
  namespace: ctfd
spec:
  storageClassName: nfs
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
