apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ctfd-db-2022-pvc
  namespace: database
spec:
  storageClassName: local
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      name: ctfd-db-2022-pv
