apiVersion: v1
kind: PersistentVolume
metadata:
  name: ctfd-2022-log-pv
  namespace: ctfd
spec:
  capacity:
    storage: 400Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  claimRef:
    name: ctfd-2022-log-pvc
    namespace: ctfd
  nfs:
    path: /mnt/nfs/ctfd/2022/log
    server: 192.168.0.20
    readOnly: no
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ctfd-2022-uploads-pv
  namespace: ctfd
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  claimRef:
    name: ctfd-2022-uploads-pvc
    namespace: ctfd
  nfs:
    path: /mnt/nfs/ctfd/2022/uploads
    server: 192.168.0.20
    readOnly: no
