apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ctfd-2022-log-pvc
  namespace: ctfd
spec:
  storageClassName: nfs
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 400Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ctfd-2022-uploads-pvc
  namespace: ctfd
spec:
  storageClassName: nfs
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
