apiVersion: v1
kind: Namespace
metadata:
  name: website
  labels:
    name: website
---
apiVersion: v1
kind: Namespace
metadata:
  name: database
  labels:
    name: database
---
apiVersion: v1
kind: Namespace
metadata:
  name: redis
  labels:
    name: redis
---
apiVersion: v1
kind: Namespace
metadata:
  name: challs
  labels:
    name: challs
