apiVersion: v1
kind: PersistentVolume
metadata:
  name: ctfd-redis-pv
  namespace: redis
  labels:
    name: ctfd-redis-pv
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "nfs"
  claimRef:
    name: redis-data-ctfd-redis-master-0
    namespace: redis
  nfs:
    path: /mnt/nfs/redis
    server: 192.168.0.20
    readOnly: no
