apiVersion: v1
kind: ConfigMap
metadata:
  name: ctfd-env-configmap
  namespace: ctfd
data:
  DB_FILE: '/etc/ctfd-db/database'
  DB_USER_FILE: '/etc/ctfd-db/username'
  DB_PASS_FILE: '/etc/ctfd-db/password'
  ACCESS_LOG: '-'
  ERROR_LOG: '-'
  UPLOAD_FOLDER: '/var/uploads'
  LOG_FOLDER: '/var/log/CTFd'
  REVERSE_PROXY: 'true'
  REDIS_URL: 'redis://ctfd-redis-master.redis.svc.cluster.local:6379'
  WORKERS: '1'
  root-pass: 'Y3RmZHJvb3RwYXNzCg=='
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
  namespace: ctfd
spec:
  rules:
  - host: ctfssi-2021.test
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: ctfd-2021-service
              port:
                number: 8000
  - host: ctfssi-2022.test
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: ctfd-2022-service
              port:
                number: 8000
