apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ctfd-2021-log-pvc
  namespace: ctfd
spec:
  storageClassName: nfs
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 400Mi
  selector:
    matchLabels:
      name: ctfd-2021-log-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ctfd-2021-uploads-pvc
  namespace: ctfd
spec:
  storageClassName: nfs
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ctfd-2021-log-pv
  namespace: ctfd
spec:
  capacity:
    storage: 400Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  claimRef:
    name: ctfd-2021-log-pvc
    namespace: ctfd
  nfs:
    path: /mnt/nfs/ctfd/2021/log
    server: 192.168.0.20
    readOnly: no
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ctfd-2021-uploads-pv
  namespace: ctfd
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  claimRef:
    name: ctfd-2021-uploads-pvc
    namespace: ctfd
  nfs:
    path: /mnt/nfs/ctfd/2021/uploads
    server: 192.168.0.20
    readOnly: no
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ctfd-2022-log-pvc
  namespace: ctfd
spec:
  storageClassName: nfs
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 400Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ctfd-2022-uploads-pvc
  namespace: ctfd
spec:
  storageClassName: nfs
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ctfd-2022-log-pv
  namespace: ctfd
spec:
  capacity:
    storage: 400Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  claimRef:
    name: ctfd-2022-log-pvc
    namespace: ctfd
  nfs:
    path: /mnt/nfs/ctfd/2022/log
    server: 192.168.0.20
    readOnly: no
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ctfd-2022-uploads-pv
  namespace: ctfd
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  claimRef:
    name: ctfd-2022-uploads-pvc
    namespace: ctfd
  nfs:
    path: /mnt/nfs/ctfd/2022/uploads
    server: 192.168.0.20
    readOnly: no
