apiVersion: v1
kind: Service
metadata:
  name: ctfd-db-2022-service
  namespace: database
  labels:
    ctfd.db.2022.service: ctfd-db-2022-service
spec:
  ports:
  - name: 'mariadb'
    port: 3306
    targetPort: 3306
  selector:
    ctfd.db.2022.pod: ctfd-db-2022-pod
