apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctfd-2021-chall-xor-otp-deployment
  namespace: challs
  labels:
    ctfd.chall.deployment: ctfd-2021-chall-xor-otp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      ctfd.chall.pod: ctfd-2021-xor-otp-pod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        ctfd.chall.pod: ctfd-2021-xor-otp-pod
    spec:
      containers:
      - image: doombringerazurai/chall-xor-otp:1.0
        name: chall-xor-otp
        ports:
        - containerPort: 47400
        resources:
          requests:
            cpu: "30m"
          limits:
            cpu: "100m"
        livenessProbe:
              tcpSocket:
                port: 8080
              initialDelaySeconds: 60
              periodSeconds: 60
      restartPolicy: Always
      tolerations:
        - key: "type"
          operator: "Equal"
          value: "challs"
          effect: "NoSchedule"
#      affinity:
#        nodeaffinity:
#          requiredduringschedulingignoredduringexecution:
#            nodeselectorterms:
#            - matchexpressions:
#              - key: type
#                operator: in
#                values:
#                -  chall-node
---
apiVersion: v1
kind: Service
metadata:
  name: ctfd-2021-chall-xor-otp-service
  namespace: challs
  labels:
    ctfd.chall.service: ctfd-2021-chall-xor-otp-service
spec:
  selector:
    ctfd.chall.pod: ctfd-2021-xor-otp-pod
  type: ClusterIP
  ports:
  - name: 'http'
    port: 47400
    targetPort: 47400
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ctfd-2021-chall-xor-otp-hpa
  labels:
    ctfd.chall.pod: ctfd-2021-xor-otp-pod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ctfd-2021-chall-xor-otp-deployment
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 10
status:
  observedGeneration: 1
  currentReplicas: 1
  desiredReplicas: 1
  currentMetrics:
  - type: Resource
    resource:
      name: cpu
      current:
        averageUtilization: 0
        averageValue: 0
