apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctfd-2022-chall-uccdi-deployment
  namespace: challs
  labels:
    ctfd.chall.deployment: ctfd-2022-chall-uccdi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      ctfd.chall.pod: ctfd-2022-uccdi-pod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        ctfd.chall.pod: ctfd-2022-uccdi-pod
    spec:
      containers:
      - image: doombringerazurai/chall-uccdi:1.0
        name: chall-uccdi
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "30m"
          limits:
            cpu: "100m"
      restartPolicy: Always
      tolerations:
        - key: "type"
          operator: "Equal"
          value: "site"
          effect: "NoSchedule"
#      affinity:
#        nodeaffinity:
#          requiredduringschedulingignoredduringexecution:
#            nodeselectorterms:
#            - matchexpressions:
#              - key: type
#                operator: in
#                values:
#                -  chall-node
---
apiVersion: v1
kind: Service
metadata:
  name: ctfd-2022-chall-uccdi-service
  labels:
    ctfd.chall.service: ctfd-2022-chall-uccdi-service
spec:
  selector:
    ctfd.chall.pod: ctfd-2022-uccdi-pod
  type: LoadBalancer
  ports:
  - name: 'http'
    port: 80
    targetPort: 80
    nodePort: 30001
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ctfd-2022-chall-uccdi-hpa
  labels:
    ctfd.chall.pod: ctfd-2022-uccdi-pod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ctfd-2022-chall-uccdi-deployment
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 10
status:
  observedGeneration: 1
  currentReplicas: 1
  desiredReplicas: 1
  currentMetrics:
  - type: Resource
    resource:
      name: cpu
      current:
        averageUtilization: 0
        averageValue: 0
